services:
  api:
    ports:
      - "3000:3000"
    command: npm run dev
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./tests
          target: /app/tests

  test:
    build: .
    attach: false
    command: npm run test:watch
    develop:
      watch:
        - action: rebuild
          path: Dockerfile

        - action: rebuild
          path: package.json

        - action: rebuild
          path: package-lock.json

        - action: sync
          path: ./src
          target: /app/src

        - action: sync
          path: ./tests
          target: /app/tests

  postgres:
    ports:
      - "5432:5432"
